[project]
name = "facts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "chromadb>=1.3.5",
  "langchain==0.0.352",
  "langchain-openai==0.0.6",
  "python-dotenv>=1.0.0",
  "tiktoken>=0.12.0",
]
